.ll 6i
.pl 10.5i
.\"	@(#)key.1	1.1 	 10/28/93
.\"
.lt 6.0i
.TH KEY 1 "28 October 1993"
.AT 3
.SH NAME
key \-  Stand\-alone program for computing responses to S/Key challenges.
.SH SYNOPSIS
.B key [\-n <count>] [\-p <password>] <Sequence> <key>
.SH DESCRIPTION
.I key
Takes the optional count  of the number of one time access
passwords to print
along with a (maximum) sequence number and key as command line args,
it prompts for the user's secret password (if not used on command line),
and produces both word and hex format responses.
.SH EXAMPLE
.sh
  Usage example:
.sp 0
 	>key \-n 5 99 th91334
.sp 0
 	Enter password: <your secret password is entered here>
.sp 0
 	OMEN US HORN OMIT BACK AHOY
.sp 0
	.... 4 more passwords.
.sp 0
 	>
.LP
.SH OPTIONS
.LP
.B \-n <count>
the number of one time access passwords to print.
The default is one.

.B \-p <password>
user's secret password.

.B \-d
debug flag, may be used 3 times to increase the information of debug messages.

.B \-l <logfile>
redirect output and debugging to the specified logfile, default is stdout.

.B \-h
display usage information.

.B \-v
display the version number.

.B \-e
turn password echoing on, default is off.

.SH DIAGNOSTICS
.SH BUGS
It is an obvious security hazard to enter your secret password on
the command line (-p option).
.LP
.SH SEE ALSO
.BR skey(1),
.BR keyinit(1),
.BR keysu(1),
.BR keyinfo(1)
.SH AUTHOR
Phil Karn, Neil M. Haller, John S. Walden, Scott Chasin
