.ll 6i
.pl 10.5i
.\"	@(#)keysh.1	1.0 	10/28/93
.\"
.lt 6.0i
.TH KEYSH 1 "28 October 1993"
.AT 3
.SH NAME
keysh \-  Authentication shell used for S/Key challenges.
.SH SYNOPSIS
.B keysh
.SH DESCRIPTION
.I keysh
is used as a user's default shell (in /etc/passwd) for authenticating a user
upon login.  This shell is normally used when the S/Key login program 
can not be used.
.sp 1
.LP
.SH DIAGNOSTICS
.SH BUGS
.LP
.SH SEE ALSO
.BR keyinit(1),
.BR skey(1),
.BR key(1)
.SH AUTHORS
Phil Karn, Neil M. Haller, John S. Walden, Scott Chasin
